openapi: 3.0.2
info:
  title: Protected API
  version: v1
paths:
  /pet:
    post:
      tags:
        - pet
      operationId: addPet
      responses:
      '200':
        description: Successful operation
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/Pet'
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      
  